### ISSUE TITLE
"wikidataLanguage" default value should be English then Russian

### ISSUE THREAD

**Issue by AtilioA** [blokhinnv/wikidataqidlabels#1]
English has more labels and is the most widely spoken language. We could use "`en|ru`" instead if you want to keep Russian. Personally, I'm a native Brazilian Portuguese speaker with no knowledge of Russian, so having it as default wasn't useful to me at all.

EDIT: nice idea, though. I've been researching Wikidata for the last few months and this came right in time :+1:

**Comment by blokhinnv** [comment]
I absolutely agree that English should be set as default language. Updated the defaults. I'm closing the issue, then. 

Thank you for your review, by the way. 👍
